---
all:
  children:
    webservers:
      hosts:
        i-0328512fbe0268206:
          ansible_connection: aws_ssm
          ansible_aws_ssm_region: eu-west-1
          ansible_aws_ssm_bucket_name: devops-lab-dev-ssm-78405367
          ansible_aws_ssm_s3_addressing_style: virtual
